[workspace]
members = [
    "crates/crow-ast",
    "crates/crow-cli",
    "crates/crow-codegen", 
    "crates/crow-collect-spec-item", 
    "crates/crow-common",
    "crates/crow-driver", 
    "crates/crow-fresh", 
    "crates/crow-hir",
    "crates/crow-lex", 
    "crates/crow-lint", 
    "crates/crow-lower-hir", 
    "crates/crow-lower-mir",
    "crates/crow-mir", 
    "crates/crow-mir-monomorph", 
    "crates/crow-mir-passes", "crates/crow-mod-codec-ty",
     "crates/crow-module-codec",
    "crates/crow-parse", 
    "crates/crow-resolving", 
    "crates/crow-tycheck", 
    "crates/crow-types",
]
resolver = "3"
doctest = false
