[package]
name = "crow-codegen"
version = "0.1.0"
edition = "2024"

[dependencies]
crow-mir = {path = "../crow-mir"}
crow-tycheck ={ path = "../crow-tycheck"}
crow-mir-monomorph = { path = "../crow-mir-monomorph" }
inkwell = { version = "0.5.0", features = ["llvm18-0"] }

[dependencies.llvm-sys]
version = "180.0.0" # Match your LLVM major version
features = ["force-dynamic"]