[package]
name = "crow-lint"
version = "0.1.0"
edition = "2024"

[dependencies]
crow-hir = { path = "../crow-hir" }
crow-lex = { path = "../crow-lex" }
crow-resolving = {path = "../crow-resolving"}
crow-tycheck = {path = "../crow-tycheck"}
miette = { git = "https://github.com/crow-rs/miette" }
thiserror = "2.0.18"