[package]
name = "crow-tycheck"
version = "0.1.0"
edition = "2024"

[dependencies]
crow-hir = { path = "../crow-hir" }
crow-resolving = { path = "../crow-resolving" }
crow-lex = { path = "../crow-lex" }
crow-ast = { path = "../crow-ast" }
crow-common = {path = "../crow-common"}
ena = "0.14.4"
miette = { git = "https://github.com/crow-rs/miette" }
thiserror = "2.0.18"
