[package]
name = "crow-driver"
version = "0.1.0"
edition = "2024"

[dependencies]
rayon = "1.12.0"
crow-parse = { path = "../crow-parse" }
crow-lex = { path = "../crow-lex" }
crow-macros = { path = "../crow-macros" }
crow-ast = { path = "../crow-ast" }
crow-resolving ={ path = "../crow-resolving"}
crow-hir ={ path = "../crow-hir"}
crow-lower-hir ={ path = "../crow-lower-hir"}
crow-tycheck ={ path = "../crow-tycheck"}
crow-lint ={ path = "../crow-lint"}
miette = { git = "https://github.com/crow-rs/miette", features = ["fancy"] }
tracing = "0.1.44"
petgraph = "0.8.3"
walkdir = "2.5.0"
thiserror = "2.0.18"
camino = "1.2.2"
